spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_schema
    username: root
    password: Abhideva@1110
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
  cloud:
    loadbalancer:
       ribbon:
        enable: true

server:
  servlet:
    context-path: /pet
  port: 9191

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    groups-order: asc
    disable-swagger-default-url: true
    docUrl: http://localhost:9191/pet
            
logging:
  level:
    org:
      hibernate:
        stat: info
        type:
          descriptor:
            sql: info